import{existsSync as N}from"node:fs";import{join as V}from"node:path";import{existsSync as O,mkdirSync as q,readFileSync as R,writeFileSync as Q}from"node:fs";import{join as T}from"node:path";var s=[2,3,4,5],c=".maencof-lens",l="config.json",d="1.0";function p(t){return typeof t=="string"&&t.length>0}function I(t){return typeof t=="number"&&Number.isInteger(t)&&t>=1&&t<=5}function M(t){if(t===null||typeof t!="object"||Array.isArray(t))return!1;let e=t;return p(e.name)&&p(e.path)}function h(t){if(t===null||typeof t!="object"||Array.isArray(t))return!1;let e=t;return!Array.isArray(e.vaults)||e.vaults.length===0?!1:e.vaults.every(M)}function k(t){if(!Array.isArray(t))return[...s];let e=t.filter(I);return e.length>0?e:[...s]}function L(t){let e=t;return{name:e.name,path:e.path,layers:k(e.layers),default:typeof e.default=="boolean"?e.default:!1}}function g(t){let e=t,n=p(e.version)?e.version:d,r=e.vaults.map(L);return{version:n,vaults:r}}function S(t){let e=T(t,c,l);if(!O(e))return null;try{let n=JSON.parse(R(e,"utf8"));return h(n)?g(n):null}catch{return null}}var i={READY:"ready",STALE:"stale",PATH_NOT_FOUND:"path not found",INDEX_NOT_BUILT:"index not built",LEGACY_V1:"legacy v1",UNKNOWN:"status unknown"};import{readdirSync as F,statSync as b}from"node:fs";import{join as G}from"node:path";import{existsSync as v,statSync as _}from"node:fs";import{join as y}from"node:path";var u={INDEX:"index.json",NODES:"nodes.json",EDGES:"edges.json",GRAPH_META:"graph-meta.json",WEIGHTS:"weights.json",SNAPSHOT:"snapshot.json",COMMUNITIES:"communities.json",STALE_NODES:"stale-nodes.json"};var E=".maencof";function A(t){try{return v(t)?_(t).mtimeMs:null}catch{return null}}function w(t){let e=y(t,E,u.GRAPH_META),n=A(e);if(n!==null)return{kind:"graph-meta",path:e,mtimeMs:n};let r=y(t,E,u.INDEX),a=A(r);return a!==null?{kind:"legacy",path:r,mtimeMs:a}:null}var P=new Set([".maencof",".maencof-meta",".maencof-lens",".git","node_modules"]);function j(t){let e=0,n=[t];for(;n.length>0;){let r=n.pop(),a;try{a=F(r,{withFileTypes:!0})}catch{continue}for(let o of a){let m=G(r,o.name);if(o.isDirectory()){if(o.name.startsWith(".")||P.has(o.name))continue;n.push(m)}else if(o.isFile()&&o.name.endsWith(".md"))try{let f=b(m).mtimeMs;f>e&&(e=f)}catch{}}}return e}function K(t){let e=Math.round(t/6e4);return e<60?`${e}m ago`:`${Math.round(e/60)}h ago`}async function x(t){let e=w(t);if(e===null)return{isStale:!0,indexMtime:null,newestFileMtime:0,staleSince:"index not found",markerKind:null};if(e.kind==="legacy")return{isStale:!0,indexMtime:e.mtimeMs,newestFileMtime:0,staleSince:"legacy v1",markerKind:"legacy"};try{let n=j(t),r=n>e.mtimeMs,a={isStale:r,indexMtime:e.mtimeMs,newestFileMtime:n,markerKind:"graph-meta"};return r&&(a.staleSince=K(n-e.mtimeMs)),a}catch{return{isStale:!0,indexMtime:e.mtimeMs,newestFileMtime:0,staleSince:"index scan failed",markerKind:"graph-meta"}}}var z=`[maencof-lens] Read-only vault access enabled.

<vaults>
{{vaults}}
</vaults>

<capabilities>
- /maencof-lens:maencof-lens-lookup <keyword> \u2014 single-doc retrieval + summary
- /maencof-lens:maencof-lens-context <query> \u2014 token-budgeted multi-doc assembly
- "vault research" or "vault explore" \u2014 autonomous researcher agent
</capabilities>

<constraints>
- Read-only. Vault writes require a maencof session.
- Layer filter: L2-L5 (L1 excluded).
</constraints>`;function C(t){return{continue:!0,hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:t}}}async function W(t){if(!N(t))return i.PATH_NOT_FOUND;try{let e=await x(t);return e.markerKind==="legacy"?i.LEGACY_V1:e.markerKind===null?i.INDEX_NOT_BUILT:e.isStale?`${i.STALE} (${e.staleSince??"unknown"})`:i.READY}catch{return i.UNKNOWN}}async function D(t){let e=V(t,c,l);if(!N(e))return{continue:!0};let n=S(t);if(!n)return C("[maencof-lens] Warning: Invalid config at .maencof-lens/config.json");let r=[];for(let a of n.vaults){let o=await W(a.path),m=a.default?" [default]":"";r.push(`- ${a.name} (${a.path})${m} \u2014 ${o}`)}return C(z.replace("{{vaults}}",r.join(`
`)))}async function U(){let t=process.cwd(),e=await D(t);e.hookSpecificOutput?.additionalContext&&process.stdout.write(JSON.stringify({hookSpecificOutput:{...e.hookSpecificOutput,hookEventName:"SessionStart"}}))}U().catch(()=>{process.exit(0)});
