import type { ConfigDiagnostic } from './configTypes.js';

const RENAMED_STRUCTURE_KEYS: Record<string, string> = {
  additionalOrganNames: 'organNames',
  additionalAllowedPeers: 'allowedPeers',
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((item) => typeof item === 'string');
}

/**
 * Lift a v2 layer to v3 without interpreting unrelated settings.
 *
 * Renames: `structure.additionalOrganNames` → `structure.organNames`,
 * `structure.additionalAllowedPeers` → `structure.allowedPeers`,
 * `structure.additionalExcludedDirectories` (bare names, scan-only) →
 * `structure.excludeFromScan` as any-depth patterns (double star, slash, name), and
 * `structure.generatedPaths` → `review.generatedPaths`. The cross-cutting
 * `ignore` list is never generated by migration.
 */
export function migrateConfigV2(
  input: Record<string, unknown>,
): { config: Record<string, unknown>; diagnostics: ConfigDiagnostic[] } {
  if (input.version !== '2.0') return { config: input, diagnostics: [] };
  const config: Record<string, unknown> = { ...input, version: '3.0' };
  if (isRecord(input.structure)) {
    const fields: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(input.structure))
      fields[RENAMED_STRUCTURE_KEYS[key] ?? key] = value;
    const names = fields.additionalExcludedDirectories;
    if (isStringArray(names)) {
      const legacyPatterns = names.map((name) => `**/${name}`);
      fields.excludeFromScan = isStringArray(fields.excludeFromScan)
        ? [...fields.excludeFromScan, ...legacyPatterns]
        : legacyPatterns;
    }
    delete fields.additionalExcludedDirectories;
    if (fields.generatedPaths !== undefined) {
      const review = isRecord(input.review) ? { ...input.review } : {};
      if (review.generatedPaths === undefined)
        review.generatedPaths = fields.generatedPaths;
      config.review = review;
      delete fields.generatedPaths;
    }
    if (Object.keys(fields).length > 0) config.structure = fields;
    else delete config.structure;
  }
  return {
    config,
    diagnostics: [
      {
        code: 'config-migration-required',
        message:
          'Config v2 was converted in memory; save through settings or run project_setup init to persist v3.',
        affects: [],
        nextAction:
          'Save through settings or run project_setup action "init" to persist a lossless v3 migration.',
      },
    ],
  };
}
