/** Persona directory inside every Codex skill-variant tree (under the skills root). */
export const PERSONA_SUBDIR = "_shared/personas";

/**
 * Does this skill-file body actually instruct spawning a persona subagent for
 * `pluginName`? Matches a quoted `subagent_type: "<plugin>:` (Task and Agent both
 * quote the string arg). The quote is required on purpose: it excludes prose that
 * merely mentions the spawn form unquoted (e.g. a schema doc's
 * `Agent(subagent_type: filid:<id>)`), which needs no rewrite. Plugin names are
 * `[a-z][a-z0-9-]*`, so no regex escaping is needed.
 */
export function containsPersonaSpawn(
  content: string,
  pluginName: string,
): boolean {
  return new RegExp(`subagent_type:\\s*["']${pluginName}:`).test(content);
}

/**
 * Rewrite a spawn-bearing skill file for Codex by prepending a host-adaptation
 * protocol: since Codex has no `subagent_type` registry, a
 * `subagent_type: "<plugin>:<id>"` spawn must instead start a `multi_agent`
 * subagent that first reads the relocated persona and adopts it. The persona path
 * is skill-relative (`../…/_shared/personas`), computed from how deep the file
 * sits under `skills/`, so it holds wherever the spawn instruction lives. The
 * block goes right after YAML frontmatter (or at the very top for sub-docs) so
 * the rule is read before any spawn step. Deterministic for a given
 * `(pluginName, relativeSkillPath)`.
 */
export function injectSpawnProtocol(
  content: string,
  relativeSkillPath: string,
  pluginName: string,
): string {
  const depth = relativeSkillPath.split("/").length - 1;
  const personaPath = `${"../".repeat(depth)}${PERSONA_SUBDIR}`;
  const block = protocolBlock(pluginName, personaPath);

  const frontmatter = content.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n/);
  if (frontmatter)
    return `${frontmatter[0]}\n${block}\n${content.slice(frontmatter[0].length)}`;
  return `${block}\n\n${content}`;
}

function protocolBlock(pluginName: string, personaPath: string): string {
  return `<!-- codex-persona-spawn (generated by @ogham/plugin-compiler — do not edit) -->

## Host adaptation — persona subagent spawns

This is the Codex build of this skill. Codex has no \`subagent_type\` persona
registry, so a \`subagent_type: "${pluginName}:<id>"\` spawn would otherwise start a
generic subagent with none of the persona's definition. Whenever a step below
spawns a subagent with \`subagent_type: "${pluginName}:<id>"\` (via \`Task\` or
\`Agent\`), do this instead — everything else about the step stays the same:

1. Spawn a \`multi_agent\` subagent.
2. Make its FIRST action to Read \`${personaPath}/<id>.md\` and adopt that persona
   definition in full as its operating contract.
3. Then carry out the original spawn's prompt, inputs, and output contract
   verbatim.

\`<id>\` is the text after \`${pluginName}:\` in the original \`subagent_type\` value
(e.g. \`subagent_type: "${pluginName}:reviewer"\` → read \`${personaPath}/reviewer.md\`).`;
}
