/** Render one validated marker phase for the Codex collaboration-tool contract. */
export function renderCodexAsyncAgentBlock(
  phase: "spawn" | "join",
  pluginName: string,
  agentId: string,
  personaPath: string,
): string {
  const role = `${pluginName}:${agentId}`;
  if (phase === "spawn")
    return `<!-- codex-async-agent:spawn (generated by @ogham/plugin-compiler — do not edit) -->

Spawn a \`multi_agent\` child for the \`${role}\` role with \`spawn_agent\`, using
\`fork_turns: "none"\`, and keep the returned target for this run. In the child
prompt, require its FIRST action to read \`${personaPath}\` and adopt that persona
definition in full, then carry out the prompt below. The child runs off-thread,
so continue any useful independent work in this turn while it runs. Do not end
this turn or send the final response before joining that target: Codex records a
completed child but does not re-invoke a parent turn that has already ended.`;

  return `<!-- codex-async-agent:join (generated by @ogham/plugin-compiler — do not edit) -->

Before sending the final response, call \`wait_agent\` for the next mailbox update.
Accept the report only when its sender belongs to the recorded child target. If
the update is unrelated or that child is still working, call \`wait_agent\` again;
never spawn a second child or end the turn expecting a completion notice to
resume it. A child that terminates without producing a report counts as
\`status: failure\` (\`error: cli_error\`) — tell the user.`;
}
