/** Render the persona-free handoffs marker selected by adaptAsyncAgentLifecycle. */
export function renderCodexHandoffLoop(): string {
  return `<!-- codex-async-agent:handoffs (generated by @ogham/plugin-compiler — do not edit) -->
After \`spawn_agent\`, keep the parent turn active; Codex does not resume an ended
turn when a child completes. Record each child target with its handoff and use
\`wait_agent\` until that child's completion arrives; timeouts or unrelated updates
mean wait again. Then continue the existing validation and next-handoff loop.
Use commentary for progress; send the final response only at the workflow's
delivery or explicit stop condition.
<!-- codex-async-agent:end -->`;
}
