/**
 * @file index.ts
 * @description @ogham/imbas public API entry point
 *
 * `mcp/` 는 재노출하지 않는다 — `mcp/server/server.ts` 가 `version.ts` 를
 * 참조하므로 재노출은 src → mcp → mcp/server → src 의존 순환이 된다.
 * MCP 서버는 esbuild 가 `mcp/serverEntry/serverEntry.ts` 에서 조립한다.
 */

export {
  CompletePhaseActionSchema,
  ComplexityGradeSchema,
  DefaultsConfigSchema,
  EscapeCodeSchema,
  EscapePhaseActionSchema,
  EstimatePhaseSchema,
  EstimationManifestSchema,
  EstimationMilestoneSchema,
  EstimationPertSchema,
  EstimationRiskSchema,
  EstimationRollupSchema,
  EstimationScheduleSchema,
  EstimationTrackSchema,
  EstimationUnitSchema,
  EstimationViewRefsSchema,
  ImbasConfigSchema,
  JiraConfigSchema,
  JiraPhaseToWorkflowSchema,
  LabelsConfigSchema,
  LanguageConfigSchema,
  LinkStatusSchema,
  LlmModelConfigSchema,
  ManifestItemStatusSchema,
  ManifestTypeSchema,
  PhaseNameSchema,
  PhasesSchema,
  PhaseStatusSchema,
  ProviderSchema,
  RefinePhaseSchema,
  RunStateSchema,
  RunTransitionSchema,
  SettingsBootstrapSchema,
  SettingsSaveBodySchema,
  SkippablePhaseSchema,
  SkipPhasesActionSchema,
  SplitPhaseSchema,
  StartPhaseActionSchema,
  StoriesManifestSchema,
  StoryItemSchema,
  StoryLinkSchema,
  StoryVerificationSchema,
  EstimationConfigSchema,
  TransitionItemSchema,
  ValidateResultSchema,
} from './types/index.js';
export type {
  ComplexityGrade,
  DefaultsConfig,
  EscapeCode,
  EstimatePhase,
  EstimationManifest,
  EstimationMilestone,
  EstimationPert,
  EstimationRisk,
  EstimationRollup,
  EstimationSchedule,
  EstimationSummary,
  EstimationTrack,
  EstimationUnit,
  EstimationViewRefs,
  ImbasConfig,
  JiraConfig,
  JiraPhaseToWorkflow,
  LabelsConfig,
  LanguageConfig,
  LinkStatus,
  LlmModelConfig,
  ManifestItemStatus,
  ManifestSummary,
  ManifestType,
  McpToolInput,
  McpToolResult,
  PhaseName,
  Phases,
  PhaseStatus,
  Provider,
  RefinePhase,
  RunState,
  RunTransition,
  SettingsBootstrap,
  SettingsPageState,
  SettingsSaveBody,
  SettingsSaveSummary,
  SettingsSettleEvent,
  SplitPhase,
  StoriesManifest,
  StoryItem,
  StoryLink,
  StoryVerification,
  EstimationConfig,
  TransitionItem,
  ValidateResult,
} from './types/index.js';
export { VERSION } from './version.js';

// Core modules
export {
  createRunState,
  loadRunState,
  saveRunState,
  applyTransition,
  loadConfig,
  saveConfig,
  getConfigValue,
  setConfigValue,
  applyConfigUpdates,
  loadManifest,
  getManifestSummary,
  getEstimationSummary,
  validateManifest,
  getImbasRoot,
  getProjectDir,
  getCacheDir,
  getRunsDir,
  getRunDir,
  generateRunId,
} from './core/index.js';

// Lib modules
export {
  createLogger,
  setLogDir,
  resetLogger,
  readJson,
  writeJson,
} from './lib/index.js';
export type { Logger } from './lib/index.js';
