/**
 * @file index.ts
 * @description @ogham/imbas public API entry point
 *
 * `mcp/` 는 재노출하지 않는다 — `mcp/server/server.ts` 가 `version.ts` 를
 * 참조하므로 재노출은 src → mcp → mcp/server → src 의존 순환이 된다.
 * MCP 서버는 esbuild 가 `mcp/serverEntry/serverEntry.ts` 에서 조립한다.
 */

export {
  CompletePhaseActionSchema,
  DefaultsConfigSchema,
  DevplanManifestSchema,
  DevplanPhaseSchema,
  EscapeCodeSchema,
  EscapePhaseActionSchema,
  ExecutionStepSchema,
  FeedbackCommentSchema,
  ImbasConfigSchema,
  JiraConfigSchema,
  JiraPhaseToWorkflowSchema,
  LabelsConfigSchema,
  LanguageConfigSchema,
  LinkStatusSchema,
  LlmModelConfigSchema,
  ManifestItemStatusSchema,
  PhaseNameSchema,
  PhasesSchema,
  PhaseStatusSchema,
  ProviderSchema,
  RunStateSchema,
  RunTransitionSchema,
  SettingsBootstrapSchema,
  SettingsSaveBodySchema,
  SplitPhaseSchema,
  StartPhaseActionSchema,
  StoriesManifestSchema,
  StoryItemSchema,
  StoryLinkSchema,
  StorySubtasksSchema,
  StoryVerificationSchema,
  SubtaskItemSchema,
  SubtaskLimitsSchema,
  TaskItemSchema,
  TransitionItemSchema,
  ValidatePhaseSchema,
  ValidateResultSchema,
} from './types/index.js';
export type {
  DefaultsConfig,
  DevplanManifest,
  DevplanPhase,
  EscapeCode,
  ExecutionStep,
  FeedbackComment,
  ImbasConfig,
  JiraConfig,
  JiraPhaseToWorkflow,
  LabelsConfig,
  LanguageConfig,
  LinkStatus,
  LlmModelConfig,
  ManifestItemStatus,
  ManifestSummary,
  McpToolInput,
  McpToolResult,
  PhaseName,
  Phases,
  PhaseStatus,
  Provider,
  RunState,
  RunTransition,
  SettingsBootstrap,
  SettingsPageState,
  SettingsSaveBody,
  SettingsSaveSummary,
  SettingsSettleEvent,
  SplitPhase,
  StoriesManifest,
  StoryItem,
  StoryLink,
  StorySubtasks,
  StoryVerification,
  SubtaskItem,
  SubtaskLimits,
  TaskItem,
  TransitionItem,
  ValidatePhase,
  ValidateResult,
} from './types/index.js';
export { VERSION } from './version.js';

// Core modules
export {
  createRunState,
  loadRunState,
  saveRunState,
  applyTransition,
  loadConfig,
  saveConfig,
  getConfigValue,
  setConfigValue,
  applyConfigUpdates,
  loadManifest,
  getManifestSummary,
  validateManifest,
  getImbasRoot,
  getProjectDir,
  getCacheDir,
  getRunsDir,
  getRunDir,
  generateRunId,
} from './core/index.js';

// Lib modules
export { createLogger, setLogDir, resetLogger, readJson, writeJson } from './lib/index.js';
export type { Logger } from './lib/index.js';
