import type { ReviewRenderInput } from '../../../../../mcp/tools/reviewState/render/reviewRenderTypes.js';

/**
 * Build a renderer fixture containing every canonical report partition.
 *
 * @returns A complete deterministic render input for report artifact tests.
 */
export function buildReviewRenderInput(): ReviewRenderInput {
  const confirmedUnknown = {
    id: 'RVW-002',
    origin: 'review',
    severity: 'warning',
    category: 'maintainability',
    path: 'src/z.ts',
    lines: 'unknown',
    rule: 'USR-Z',
    message: 'Preserve **this** claim `verbatim` | including: punctuation.',
    verdict: 'CONFIRMED',
    decisionEvidence: 'Reproduced through the public entry point.',
    decisionReason: 'The claimed behavior remains observable.',
    findingEvidence: 'src/z.ts:unknown retains the ambiguous call.',
    consequence: 'The caller receives an ambiguous result.',
    recommendedAction: 'Make the return state explicit.',
  } as const;
  const refuted = {
    id: 'FCA-001',
    origin: 'fca',
    severity: 'warning',
    category: 'structure',
    path: 'src/b.ts',
    lines: 'unknown',
    rule: 'FCA-boundary',
    message: 'The changed path crosses a fractal boundary.',
    verdict: 'REFUTED',
    decisionEvidence: 'The consumer imports the owning entry point.',
    decisionReason: 'The reported edge is within the owner subtree.',
    findingEvidence: null,
    consequence: null,
    recommendedAction: null,
  } as const;
  const confirmedLocated = {
    id: 'RVW-001',
    origin: 'review',
    severity: 'error',
    category: 'bug',
    path: 'src/a.ts',
    lines: '12-14',
    rule: 'USR-A',
    message: 'The returned value drops the validated branch.',
    verdict: 'CONFIRMED',
    decisionEvidence: 'The failing branch was independently reproduced.',
    decisionReason: 'The exact committed lines return the wrong value.',
    findingEvidence: 'src/a.ts:12-14 returns false for the valid input.',
    consequence: 'Valid callers receive a rejection.',
    recommendedAction: 'Return the validated branch result.',
  } as const;
  const indeterminate = {
    id: 'RVW-003',
    origin: 'review',
    severity: 'error',
    category: 'contract',
    path: 'src/c.ts',
    lines: '30',
    rule: 'USR-C',
    message: 'The public response may omit the required field.',
    verdict: 'INDETERMINATE',
    decisionEvidence: 'The external service was unavailable.',
    decisionReason: 'The claim could not be reproduced or refuted.',
    findingEvidence: 'src/c.ts:30 reads the service response.',
    consequence: 'The public contract may be incomplete.',
    recommendedAction: 'Verify the response against a recorded fixture.',
  } as const;

  return {
    branchName: 'feature/render-v7',
    baseRef: 'main',
    reviewDirectory: '.metadata/filid/reviews/feature-render-v7',
    generatedAt: '2026-09-04T12:34:56.000Z',
    evidence: {
      sourceHash: 'source-hash-v7',
      snapshotHash: 'snapshot-hash-v7',
      evidenceComplete: true,
      structureStatus: 'ok',
      verificationStatus: 'violations',
      worktree: 'clean',
    },
    files: [
      {
        path: 'src/a.ts',
        change: 'M',
        insertions: 4,
        deletions: 1,
        binary: false,
        role: 'source',
        owner: 'src',
        skipReason: null,
        rules: ['default', 'USR-A'],
        repositoryRules: [],
      },
      {
        path: 'src/c.ts',
        change: 'A',
        insertions: 2,
        deletions: 0,
        binary: false,
        role: 'source',
        owner: 'src',
        skipReason: null,
        rules: ['default', 'USR-C'],
        repositoryRules: [],
      },
      {
        path: 'public/generated.js',
        change: 'M',
        insertions: 1,
        deletions: 1,
        binary: false,
        role: 'generated',
        owner: null,
        skipReason: 'generated path',
        rules: [],
        repositoryRules: [],
      },
    ],
    fold: {
      verdict: 'REQUEST_CHANGES',
      checklist: [
        {
          path: 'src/a.ts',
          change: 'M',
          groups: ['01'],
          result: 'reviewed',
          reason: '',
        },
        {
          path: 'src/c.ts',
          change: 'A',
          groups: ['02'],
          result: 'pending',
          reason: 'missing decision',
        },
        {
          path: 'public/generated.js',
          change: 'M',
          groups: [],
          result: 'skipped',
          reason: 'generated path',
        },
      ],
      decisions: [confirmedUnknown, refuted, confirmedLocated, indeterminate],
      confirmed: [confirmedUnknown, confirmedLocated],
      refuted: [refuted],
      indeterminate: [indeterminate],
      unresolved: [
        {
          source: 'review gap',
          path: 'src/gap.ts',
          rule: 'USR-GAP',
          detail: 'required runtime evidence was unavailable',
          affectsVerdict: true,
        },
        {
          source: 'informational',
          path: 'src/info.ts',
          rule: 'FCA-INFO',
          detail: 'the touched owner also exposes an optional adapter',
          affectsVerdict: false,
        },
        {
          source: 'group 03',
          path: 'opinions/review-03.json',
          rule: 'artifact trust',
          detail: 'artifact not validated',
          affectsVerdict: true,
        },
        {
          source: 'verification',
          path: 'src/c.ts',
          rule: 'USR-C',
          detail: 'missing decision',
          affectsVerdict: true,
        },
      ],
      filesTotal: 3,
      filesReviewed: 1,
      filesSkipped: 1,
    },
  };
}
