#!/usr/bin/env node
import{createHash as v}from"node:crypto";import{existsSync as E,mkdirSync as w,readFileSync as F,readdirSync as ft,statSync as dt,unlinkSync as mt,writeFileSync as j}from"node:fs";import{homedir as U}from"node:os";import{join as g}from"node:path";function H(t){return v("sha256").update(t).digest("hex").slice(0,12)}function _(t){let n=process.env.CLAUDE_CONFIG_DIR??g(U(),".claude");return g(n,"plugins","maencof",H(t))}function S(t,n){let e=_(t),r=g(e,"turn-context");try{E(e)||w(e,{recursive:!0}),j(r,n,"utf-8")}catch{}}function N(t){let n=g(_(t),"pinned-nodes.json");try{if(!E(n))return[];let e=F(n,"utf-8"),r=JSON.parse(e);return Array.isArray(r)?r:[]}catch{return[]}}import{existsSync as C,mkdirSync as J,readFileSync as X,writeFileSync as Y}from"node:fs";import{dirname as B,join as W}from"node:path";var h=".maencof",p=".maencof-meta";var G="error-log.json",V=200;function I(t){return W(t,p,G)}function q(t){let n=B(t);C(n)||J(n,{recursive:!0})}function z(t){let n=I(t);if(!C(n))return[];try{return JSON.parse(X(n,"utf-8"))}catch{return[]}}function Q(t,n){let e=z(t);for(e.push(n);e.length>V;)e.shift();let r=I(t);q(r),Y(r,JSON.stringify(e,null,2),"utf-8")}function A(t,n){try{Q(t,n)}catch{}}import{existsSync as P}from"node:fs";import{join as b}from"node:path";function T(t){return P(b(t,h))||P(b(t,p))}async function O(){let t=[];for await(let n of process.stdin)t.push(n);return Buffer.concat(t).toString("utf-8")}function M(t){process.stdout.write(JSON.stringify(t))}var R=new Set(["create","update","delete","move","capture_insight","boundary_create","claudemd_merge","claudemd_remove"]);import{existsSync as l,readFileSync as f}from"node:fs";import{join as d}from"node:path";function $(t){if(t===null||typeof t!="object")return!1;let n=t;return typeof n.schema_version=="number"&&n.schema_version>=1&&typeof n.name=="string"&&n.name.length>0&&typeof n.greeting=="string"&&n.greeting.length>0}function K(t){let n=d(t,".maencof","index.json"),e={totalNodes:0,layerCounts:{}};try{if(!l(n))return e;let r=f(n,"utf-8"),o=JSON.parse(r),i=[];Array.isArray(o.nodes)?i=o.nodes:o.nodes&&typeof o.nodes=="object"&&(i=Object.values(o.nodes)),e.totalNodes=i.length;for(let s of i){let a=typeof s.layer=="number"?s.layer:0;e.layerCounts[a]=(e.layerCounts[a]??0)+1}}catch{}return e}function Z(t){let n=d(t,".maencof","stale-nodes.json");try{if(!l(n))return 0;let e=f(n,"utf-8"),r=JSON.parse(e);return Array.isArray(r.paths)?r.paths.length:0}catch{return 0}}function tt(t){let n=d(t,".maencof-meta","companion-identity.json");try{if(!l(n))return null;let e=JSON.parse(f(n,"utf-8"));return $(e)?e:null}catch{return null}}function nt(t,n=150){let e=t.replace(/^---[\s\S]*?---\n?/,""),r=e.split(`
`),o=[],i=!1;for(let u of r){if(!i){if(u.startsWith("#")||u.trim()==="")continue;i=!0}o.push(u)}e=o.join(`
`);let a=(e.split(/\n\n/)[0]??"").replace(/\n/g," ").trim();return a.length>n?a.slice(0,n):a}function et(t){let n=d(t,".maencof","index.json");try{if(!l(n))return"";let e=JSON.parse(f(n,"utf-8")),r=[];Array.isArray(e.nodes)?r=e.nodes:e.nodes&&typeof e.nodes=="object"&&(r=Object.values(e.nodes));let o=r.filter(s=>s.layer===1);if(o.length===0)return"";let i=[];for(let s of o)if(!(!s.path||!s.title))try{let a=d(t,s.path);if(!l(a))continue;let u=f(a,"utf-8"),c=nt(u),m=s.tags&&s.tags.length>0?` | tags: ${s.tags.slice(0,3).join(",")}`:"";i.push(`[${s.title}]: ${c}${m}`)}catch{}return i.join(`
`)}catch{return""}}function rt(t){let e=`<companion-identity>
  ${t.role?`You are ${t.name}, a ${t.role}.`:`You are ${t.name}.`}`;if(t.personality){let{tone:r,approach:o,traits:i}=t.personality,s=r?` tone="${r}"`:"",a=o?` approach="${o}"`:"",u=i?.length?i.join(","):"";e+=`
  <personality${s}${a}>${u}</personality>`}return t.principles?.length&&(e+=`
  <principles>${t.principles.join(" | ")}</principles>`),t.taboos?.length&&(e+=`
  <taboos>${t.taboos.join(" | ")}</taboos>`),e+=`
</companion-identity>`,e}function ot(t){return[1,2,3,4,5].map(n=>`L${n}:${t[n]??0}`).join(",")}function st(t){return t.map(n=>n.title).join(",")}function L(t){let{totalNodes:n,layerCounts:e}=K(t),r=Z(t),o=tt(t),i=N(t),s=n>0?Math.round((n-r)/n*100):100,a=o?` vault="${o.name}"`:"",u=st(i),c=[];o&&c.push(rt(o)),c.push(`<kg-core${a} nodes="${n}" fresh="${s}%" layers="${ot(e)}" stale="${r}">`),c.push(`  <pinned>${u}</pinned>`);let m=et(t);m&&c.push(`  <l1-core>
${m}
  </l1-core>`),c.push("</kg-core>"),c.push("<kg-directive>When encountering ambiguous or domain-specific terms, autonomously search the knowledge graph using kg_search before responding. For topics beyond L1 core knowledge, use kg_navigate to explore L2+ layers. Use kg_context for complex queries \u2014 it returns relevant content snippets from top documents. Prefer kg_context over kg_search + read when you need content from multiple related documents.</kg-directive>");let y=n>0?Math.round(r/n*100):0;return y>10&&c.push(`<kg-stale-advisory threshold="exceeded" stale="${r}/${n}" ratio="${y}%">ACTION REQUIRED: Run kg_build to rebuild the knowledge graph index. Stale ratio exceeds ${10}%. Search results may be inaccurate until rebuilt.</kg-stale-advisory>`),c.join(`
`)}function k(t){let n=t.cwd??process.cwd(),e=t.tool_name??"";if(!T(n))return{continue:!0};if(!R.has(e))return{continue:!0};try{let r=L(n);S(n,r)}catch(r){A(n,{hook:"cache-updater",error:String(r),timestamp:new Date().toISOString()})}return{continue:!0}}var it=await O(),x;try{let t=JSON.parse(it);x=k(t)}catch{x={continue:!0}}M(x);
