#!/usr/bin/env node
import{createHash as j}from"node:crypto";import{existsSync as y,mkdirSync as M,readFileSync as T,readdirSync as G,statSync as Q,unlinkSync as K,writeFileSync as F}from"node:fs";import{homedir as O}from"node:os";import{join as m}from"node:path";function R(t){return j("sha256").update(t).digest("hex").slice(0,12)}function x(t){let n=process.env.CLAUDE_CONFIG_DIR??m(O(),".claude");return m(n,"plugins","maencof",R(t))}function b(t,n){let e=x(t),r=m(e,"turn-context");try{y(e)||M(e,{recursive:!0}),F(r,n,"utf-8")}catch{}}function P(t){let n=m(x(t),"pinned-nodes.json");try{if(!y(n))return[];let e=T(n,"utf-8"),r=JSON.parse(e);return Array.isArray(r)?r:[]}catch{return[]}}import{existsSync as _}from"node:fs";import{join as C}from"node:path";var D=".maencof-meta",E=".maencof";function N(t){return _(C(t,E))||_(C(t,D))}async function $(){let t=[];for await(let n of process.stdin)t.push(n);return Buffer.concat(t).toString("utf-8")}function S(t){process.stdout.write(JSON.stringify(t))}var k=new Set(["maencof_create","maencof_update","maencof_delete","maencof_move","maencof_capture_insight","boundary_create","claudemd_merge","claudemd_remove"]);import{existsSync as l,readFileSync as p}from"node:fs";import{join as d}from"node:path";function I(t){if(t===null||typeof t!="object")return!1;let n=t;return typeof n.schema_version=="number"&&n.schema_version>=1&&typeof n.name=="string"&&n.name.length>0&&typeof n.greeting=="string"&&n.greeting.length>0}var w=10;function L(t){let n=d(t,".maencof","index.json"),e={totalNodes:0,layerCounts:{}};try{if(!l(n))return e;let r=p(n,"utf-8"),o=JSON.parse(r),i=[];Array.isArray(o.nodes)?i=o.nodes:o.nodes&&typeof o.nodes=="object"&&(i=Object.values(o.nodes)),e.totalNodes=i.length;for(let s of i){let a=typeof s.layer=="number"?s.layer:0;e.layerCounts[a]=(e.layerCounts[a]??0)+1}}catch{}return e}function U(t){let n=d(t,".maencof","stale-nodes.json");try{if(!l(n))return 0;let e=p(n,"utf-8"),r=JSON.parse(e);return Array.isArray(r.paths)?r.paths.length:0}catch{return 0}}function J(t){let n=d(t,".maencof-meta","companion-identity.json");try{if(!l(n))return null;let e=JSON.parse(p(n,"utf-8"));return I(e)?e:null}catch{return null}}function B(t,n=150){let e=t.replace(/^---[\s\S]*?---\n?/,""),r=e.split(`
`),o=[],i=!1;for(let u of r){if(!i){if(u.startsWith("#")||u.trim()==="")continue;i=!0}o.push(u)}e=o.join(`
`);let a=(e.split(/\n\n/)[0]??"").replace(/\n/g," ").trim();return a.length>n?a.slice(0,n):a}function H(t){let n=d(t,".maencof","index.json");try{if(!l(n))return"";let e=JSON.parse(p(n,"utf-8")),r=[];Array.isArray(e.nodes)?r=e.nodes:e.nodes&&typeof e.nodes=="object"&&(r=Object.values(e.nodes));let o=r.filter(s=>s.layer===1);if(o.length===0)return"";let i=[];for(let s of o)if(!(!s.path||!s.title))try{let a=d(t,s.path);if(!l(a))continue;let u=p(a,"utf-8"),c=B(u),f=s.tags&&s.tags.length>0?` | tags: ${s.tags.slice(0,3).join(",")}`:"";i.push(`[${s.title}]: ${c}${f}`)}catch{}return i.join(`
`)}catch{return""}}function W(t){let e=`<companion-identity>
  ${t.role?`You are ${t.name}, a ${t.role}.`:`You are ${t.name}.`}`;if(t.personality){let{tone:r,approach:o,traits:i}=t.personality,s=r?` tone="${r}"`:"",a=o?` approach="${o}"`:"",u=i?.length?i.join(","):"";e+=`
  <personality${s}${a}>${u}</personality>`}return t.principles?.length&&(e+=`
  <principles>${t.principles.join(" | ")}</principles>`),t.taboos?.length&&(e+=`
  <taboos>${t.taboos.join(" | ")}</taboos>`),e+=`
</companion-identity>`,e}function V(t){return[1,2,3,4,5].map(n=>`L${n}:${t[n]??0}`).join(",")}function Y(t){return t.map(n=>n.title).join(",")}function v(t){let{totalNodes:n,layerCounts:e}=L(t),r=U(t),o=J(t),i=P(t),s=n>0?Math.round((n-r)/n*100):100,a=o?` vault="${o.name}"`:"",u=Y(i),c=[];o&&c.push(W(o)),c.push(`<kg-core${a} nodes="${n}" fresh="${s}%" layers="${V(e)}" stale="${r}">`),c.push(`  <pinned>${u}</pinned>`);let f=H(t);f&&c.push(`  <l1-core>
${f}
  </l1-core>`),c.push("</kg-core>"),c.push("<kg-directive>When encountering ambiguous or domain-specific terms, autonomously search the knowledge graph using kg_search before responding. For topics beyond L1 core knowledge, use kg_navigate to explore L2+ layers. Use kg_context for complex queries \u2014 it returns relevant content snippets from top documents. Prefer kg_context over kg_search + maencof_read when you need content from multiple related documents.</kg-directive>");let h=n>0?Math.round(r/n*100):0;return h>w&&c.push(`<kg-stale-advisory threshold="exceeded" stale="${r}/${n}" ratio="${h}%">ACTION REQUIRED: Run kg_build to rebuild the knowledge graph index. Stale ratio exceeds ${w}%. Search results may be inaccurate until rebuilt.</kg-stale-advisory>`),c.join(`
`)}function A(t){let n=t.cwd??process.cwd(),e=t.tool_name??"";if(!N(n))return{continue:!0};if(!k.has(e))return{continue:!0};try{let r=v(n);b(n,r)}catch{}return{continue:!0}}var X=await $(),g;try{let t=JSON.parse(X);g=A(t)}catch{g={continue:!0}}S(g);
