#!/usr/bin/env node
import{createHash as D}from"node:crypto";import{existsSync as _,mkdirSync as k,readFileSync as w,readdirSync as Z,statSync as tt,unlinkSync as nt,writeFileSync as v}from"node:fs";import{homedir as F}from"node:os";import{join as m}from"node:path";function j(t){return D("sha256").update(t).digest("hex").slice(0,12)}function C(t){let n=process.env.CLAUDE_CONFIG_DIR??m(F(),".claude");return m(n,"plugins","maencof",j(t))}function N(t,n){let e=C(t),r=m(e,"turn-context");try{_(e)||k(e,{recursive:!0}),v(r,n,"utf-8")}catch{}}function S(t){let n=m(C(t),"pinned-nodes.json");try{if(!_(n))return[];let e=w(n,"utf-8"),r=JSON.parse(e);return Array.isArray(r)?r:[]}catch{return[]}}import{existsSync as E}from"node:fs";import{join as I}from"node:path";var g=".maencof",h=".maencof-meta";function P(t){return E(I(t,g))||E(I(t,h))}async function A(){let t=[];for await(let n of process.stdin)t.push(n);return Buffer.concat(t).toString("utf-8")}function b(t){process.stdout.write(JSON.stringify(t))}var T=new Set(["create","update","delete","move","capture_insight","boundary_create","claudemd_merge","claudemd_remove"]);import{existsSync as p,readFileSync as l}from"node:fs";import{join as d}from"node:path";function $(t){if(t===null||typeof t!="object")return!1;let n=t;return typeof n.schema_version=="number"&&n.schema_version>=1&&typeof n.name=="string"&&n.name.length>0&&typeof n.greeting=="string"&&n.greeting.length>0}function L(t){let n=d(t,".maencof","index.json"),e={totalNodes:0,layerCounts:{}};try{if(!p(n))return e;let r=l(n,"utf-8"),o=JSON.parse(r),i=[];Array.isArray(o.nodes)?i=o.nodes:o.nodes&&typeof o.nodes=="object"&&(i=Object.values(o.nodes)),e.totalNodes=i.length;for(let s of i){let a=typeof s.layer=="number"?s.layer:0;e.layerCounts[a]=(e.layerCounts[a]??0)+1}}catch{}return e}function U(t){let n=d(t,".maencof","stale-nodes.json");try{if(!p(n))return 0;let e=l(n,"utf-8"),r=JSON.parse(e);return Array.isArray(r.paths)?r.paths.length:0}catch{return 0}}function H(t){let n=d(t,".maencof-meta","companion-identity.json");try{if(!p(n))return null;let e=JSON.parse(l(n,"utf-8"));return $(e)?e:null}catch{return null}}function J(t,n=150){let e=t.replace(/^---[\s\S]*?---\n?/,""),r=e.split(`
`),o=[],i=!1;for(let u of r){if(!i){if(u.startsWith("#")||u.trim()==="")continue;i=!0}o.push(u)}e=o.join(`
`);let a=(e.split(/\n\n/)[0]??"").replace(/\n/g," ").trim();return a.length>n?a.slice(0,n):a}function X(t){let n=d(t,".maencof","index.json");try{if(!p(n))return"";let e=JSON.parse(l(n,"utf-8")),r=[];Array.isArray(e.nodes)?r=e.nodes:e.nodes&&typeof e.nodes=="object"&&(r=Object.values(e.nodes));let o=r.filter(s=>s.layer===1);if(o.length===0)return"";let i=[];for(let s of o)if(!(!s.path||!s.title))try{let a=d(t,s.path);if(!p(a))continue;let u=l(a,"utf-8"),c=J(u),f=s.tags&&s.tags.length>0?` | tags: ${s.tags.slice(0,3).join(",")}`:"";i.push(`[${s.title}]: ${c}${f}`)}catch{}return i.join(`
`)}catch{return""}}function Y(t){let e=`<companion-identity>
  ${t.role?`You are ${t.name}, a ${t.role}.`:`You are ${t.name}.`}`;if(t.personality){let{tone:r,approach:o,traits:i}=t.personality,s=r?` tone="${r}"`:"",a=o?` approach="${o}"`:"",u=i?.length?i.join(","):"";e+=`
  <personality${s}${a}>${u}</personality>`}return t.principles?.length&&(e+=`
  <principles>${t.principles.join(" | ")}</principles>`),t.taboos?.length&&(e+=`
  <taboos>${t.taboos.join(" | ")}</taboos>`),e+=`
</companion-identity>`,e}function B(t){return[1,2,3,4,5].map(n=>`L${n}:${t[n]??0}`).join(",")}function W(t){return t.map(n=>n.title).join(",")}function O(t){let{totalNodes:n,layerCounts:e}=L(t),r=U(t),o=H(t),i=S(t),s=n>0?Math.round((n-r)/n*100):100,a=o?` vault="${o.name}"`:"",u=W(i),c=[];o&&c.push(Y(o)),c.push(`<kg-core${a} nodes="${n}" fresh="${s}%" layers="${B(e)}" stale="${r}">`),c.push(`  <pinned>${u}</pinned>`);let f=X(t);f&&c.push(`  <l1-core>
${f}
  </l1-core>`),c.push("</kg-core>"),c.push("<kg-directive>When encountering ambiguous or domain-specific terms, autonomously search the knowledge graph using kg_search before responding. For topics beyond L1 core knowledge, use kg_navigate to explore L2+ layers. Use kg_context for complex queries \u2014 it returns relevant content snippets from top documents. Prefer kg_context over kg_search + read when you need content from multiple related documents.</kg-directive>");let y=n>0?Math.round(r/n*100):0;return y>10&&c.push(`<kg-stale-advisory threshold="exceeded" stale="${r}/${n}" ratio="${y}%">ACTION REQUIRED: Run kg_build to rebuild the knowledge graph index. Stale ratio exceeds ${10}%. Search results may be inaccurate until rebuilt.</kg-stale-advisory>`),c.join(`
`)}function R(t){let n=t.cwd??process.cwd(),e=t.tool_name??"";if(!P(n))return{continue:!0};if(!T.has(e))return{continue:!0};try{let r=O(n);N(n,r)}catch{}return{continue:!0}}var V=await A(),x;try{let t=JSON.parse(V);x=R(t)}catch{x={continue:!0}}b(x);
