#!/usr/bin/env node
import{existsSync as h,mkdirSync as q,readFileSync as Q,readdirSync as Z,statSync as tt,unlinkSync as et,writeFileSync as nt}from"node:fs";import{join as T}from"node:path";import{appendFileSync as L,existsSync as j,mkdirSync as H,writeFileSync as U}from"node:fs";import{dirname as Y,join as x}from"node:path";var d=".maencof",l=".maencof-meta",_="dailynotes";function X(t){return x(t,".maencof-meta",_)}function G(t,n){let r=n??$(new Date);return x(X(t),`${r}.md`)}function J(t){let n=t.path?` \u2192 ${t.path}`:"";return`- **[${t.time}]** \`${t.category}\` ${t.description}${n}`}function D(t,n){let r=G(t),o=Y(r);H(o,{recursive:!0});let e=J(n);if(j(r))L(r,e+`
`,"utf-8");else{let i=`# Dailynote \u2014 ${$(new Date)}

## Activity Log

`;U(r,i+e+`
`,"utf-8")}}function E(t){let n=String(t.getHours()).padStart(2,"0"),r=String(t.getMinutes()).padStart(2,"0");return`${n}:${r}`}function $(t){let n=t.getFullYear(),r=String(t.getMonth()+1).padStart(2,"0"),o=String(t.getDate()).padStart(2,"0");return`${n}-${r}-${o}`}import{createHash as v}from"node:crypto";import{existsSync as A,mkdirSync as Et,readFileSync as $t,readdirSync as At,statSync as kt,unlinkSync as k,writeFileSync as vt}from"node:fs";import{homedir as V}from"node:os";import{join as f}from"node:path";function W(t){return v("sha256").update(t).digest("hex").slice(0,12)}function B(t){return v("sha256").update(t).digest("hex").slice(0,12)}function K(t){let n=process.env.CLAUDE_CONFIG_DIR??f(V(),".claude");return f(n,"plugins","maencof",W(t))}function C(t,n){let r=K(n),o=B(t),e=f(r,`session-context-${o}`),s=f(r,`prompt-context-${o}`);try{A(e)&&k(e)}catch{}try{A(s)&&k(s)}catch{}}import{existsSync as N}from"node:fs";import{join as g}from"node:path";function O(t){return N(g(t,d))||N(g(t,l))}function y(t,...n){return g(t,l,...n)}function w(t,...n){return g(t,d,...n)}async function F(){let t=[];for await(let n of process.stdin)t.push(n);return Buffer.concat(t).toString("utf-8")}function I(t){process.stdout.write(JSON.stringify(t))}function P(t){let n=t.cwd??process.cwd();if(!O(n))return{continue:!0};let r=y(n,"sessions"),o=rt(t,n);if(o!==null){it(r);let e=st(),s=T(r,e);try{nt(s,o,"utf-8")}catch{}}try{let e=t.session_id??"";e&&C(e,n)}catch{}ot(r);try{let e=t.skills_used??[],s=t.files_modified??[],i=[];s.length>0&&i.push(`files: ${s.length}`),e.length>0&&i.push(`skills: ${e.join(", ")}`);let a=i.length>0?` (${i.join(", ")})`:"";D(n,{time:E(new Date),category:"session",description:`Session ended${a}`})}catch{}return{continue:!0}}function rt(t,n){let r=new Date().toISOString(),e=["# Session Summary","",`- **Session ID**: ${t.session_id??"unknown"}`,`- **Ended at**: ${r}`,""],s=t.skills_used??[];if(s.length>0){e.push("## Skills Used"),e.push("");for(let c of s)e.push(`- ${c}`);e.push("")}let i=t.files_modified??[];if(i.length>0){e.push("## Files Modified"),e.push("");for(let c of i)e.push(`- ${c}`);e.push("")}let a=M(y(n,"usage-stats.json")),u=M(w(n,"stale-nodes.json")),m=a!==null&&Object.keys(a).length>0,p=u!==null&&Array.isArray(u.paths)&&u.paths.length>0,R=s.length>0||i.length>0;if(!(m||p||R))return null;if(m){e.push("## Vault Tool Usage (Cumulative)"),e.push("");for(let[c,b]of Object.entries(a))e.push(`- ${c}: ${b}`);e.push("")}if(p){e.push("## Pending Index Updates (Stale Nodes)"),e.push("");for(let c of u.paths)e.push(`- ${c}`);e.push("")}return(m||p)&&(e.push("> Per-session statistics will be improved in a future release."),e.push("")),e.join(`
`)}function M(t){if(!h(t))return null;try{return JSON.parse(Q(t,"utf-8"))}catch{return null}}function st(){let t=new Date,n=t.getFullYear(),r=String(t.getMonth()+1).padStart(2,"0"),o=String(t.getDate()).padStart(2,"0"),e=String(t.getHours()).padStart(2,"0"),s=String(t.getMinutes()).padStart(2,"0"),i=String(t.getSeconds()).padStart(2,"0");return`${n}-${r}-${o}-${e}${s}${i}.md`}function ot(t){if(!h(t))return;let n=30*24*60*60*1e3,r=Date.now();try{let o=Z(t).filter(e=>e.endsWith(".md"));for(let e of o){let s=T(t,e);try{let i=tt(s);r-i.mtimeMs>n&&et(s)}catch{}}}catch{}}function it(t){h(t)||q(t,{recursive:!0})}var ct=await F(),S;try{let t=JSON.parse(ct);S=P(t)}catch{S={continue:!0}}I(S);
