#!/usr/bin/env node
import{existsSync as p,mkdirSync as z,readFileSync as q,readdirSync as Q,statSync as Z,unlinkSync as tt,writeFileSync as et}from"node:fs";import{join as b}from"node:path";import{appendFileSync as M,existsSync as j,mkdirSync as L,writeFileSync as H}from"node:fs";import{dirname as U,join as h}from"node:path";var Y="dailynotes";function J(t){return h(t,".maencof-meta",Y)}function G(t,n){let r=n??_(new Date);return h(J(t),`${r}.md`)}function V(t){let n=t.path?` \u2192 ${t.path}`:"";return`- **[${t.time}]** \`${t.category}\` ${t.description}${n}`}function S(t,n){let r=G(t),i=U(r);L(i,{recursive:!0});let e=V(n);if(j(r))M(r,e+`
`,"utf-8");else{let s=`# Dailynote \u2014 ${_(new Date)}

## Activity Log

`;H(r,s+e+`
`,"utf-8")}}function x(t){let n=String(t.getHours()).padStart(2,"0"),r=String(t.getMinutes()).padStart(2,"0");return`${n}:${r}`}function _(t){let n=t.getFullYear(),r=String(t.getMonth()+1).padStart(2,"0"),i=String(t.getDate()).padStart(2,"0");return`${n}-${r}-${i}`}import{createHash as E}from"node:crypto";import{existsSync as D,mkdirSync as yt,readFileSync as ht,readdirSync as St,statSync as xt,unlinkSync as $,writeFileSync as _t}from"node:fs";import{homedir as W}from"node:os";import{join as l}from"node:path";function B(t){return E("sha256").update(t).digest("hex").slice(0,12)}function X(t){return E("sha256").update(t).digest("hex").slice(0,12)}function K(t){let n=process.env.CLAUDE_CONFIG_DIR??l(W(),".claude");return l(n,"plugins","maencof",B(t))}function k(t,n){let r=K(n),i=X(t),e=l(r,`session-context-${i}`),o=l(r,`prompt-context-${i}`);try{D(e)&&$(e)}catch{}try{D(o)&&$(o)}catch{}}import{existsSync as v}from"node:fs";import{join as f}from"node:path";var w=".maencof-meta",A=".maencof";function F(t){return v(f(t,A))||v(f(t,w))}function m(t,...n){return f(t,w,...n)}function C(t,...n){return f(t,A,...n)}async function P(){let t=[];for await(let n of process.stdin)t.push(n);return Buffer.concat(t).toString("utf-8")}function N(t){process.stdout.write(JSON.stringify(t))}var nt=30;function T(t){let n=t.cwd??process.cwd();if(!F(n))return{continue:!0};let r=m(n,"sessions");it(r);let i=rt(t,n),e=st(),o=b(r,e);try{et(o,i,"utf-8")}catch{}try{let s=t.session_id??"";s&&k(s,n)}catch{}ot(r);try{let s=t.skills_used??[],u=t.files_modified??[],c=[];u.length>0&&c.push(`files: ${u.length}`),s.length>0&&c.push(`skills: ${s.join(", ")}`);let d=c.length>0?` (${c.join(", ")})`:"";S(n,{time:x(new Date),category:"session",description:`Session ended${d}`})}catch{}return{continue:!0}}function rt(t,n){let r=new Date().toISOString(),e=["# Session Summary","",`- **Session ID**: ${t.session_id??"unknown"}`,`- **Ended at**: ${r}`,""],o=t.skills_used??[];if(o.length>0){e.push("## Skills Used"),e.push("");for(let a of o)e.push(`- ${a}`);e.push("")}let s=t.files_modified??[];if(s.length>0){e.push("## Files Modified"),e.push("");for(let a of s)e.push(`- ${a}`);e.push("")}let u=O(m(n,"usage-stats.json")),c=O(C(n,"stale-nodes.json")),d=u!==null&&Object.keys(u).length>0,g=c!==null&&Array.isArray(c.paths)&&c.paths.length>0;if(d){e.push("## Vault Tool Usage (Cumulative)"),e.push("");for(let[a,R]of Object.entries(u))e.push(`- ${a}: ${R}`);e.push("")}if(g){e.push("## Pending Index Updates (Stale Nodes)"),e.push("");for(let a of c.paths)e.push(`- ${a}`);e.push("")}let I=o.length>0||s.length>0;return!d&&!g&&!I&&(e.push("> No activity recorded in this session."),e.push("")),(d||g)&&(e.push("> Per-session statistics will be improved in a future release."),e.push("")),e.join(`
`)}function O(t){if(!p(t))return null;try{return JSON.parse(q(t,"utf-8"))}catch{return null}}function st(){let t=new Date,n=t.getFullYear(),r=String(t.getMonth()+1).padStart(2,"0"),i=String(t.getDate()).padStart(2,"0"),e=String(t.getHours()).padStart(2,"0"),o=String(t.getMinutes()).padStart(2,"0"),s=String(t.getSeconds()).padStart(2,"0");return`${n}-${r}-${i}-${e}${o}${s}.md`}function ot(t){if(!p(t))return;let n=nt*24*60*60*1e3,r=Date.now();try{let i=Q(t).filter(e=>e.endsWith(".md"));for(let e of i){let o=b(t,e);try{let s=Z(o);r-s.mtimeMs>n&&tt(o)}catch{}}}catch{}}function it(t){p(t)||z(t,{recursive:!0})}var ct=await P(),y;try{let t=JSON.parse(ct);y=T(t)}catch{y={continue:!0}}N(y);
