#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();

const SEMVER_REGEX =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/;

function readPackageVersion() {
  const packageJsonPath = join(ROOT, "package.json");

  try {
    const content = readFileSync(packageJsonPath, "utf-8");
    const pkg = JSON.parse(content);

    if (!pkg.version) {
      console.error("❌ Error: No version field found in package.json");
      process.exit(1);
    }

    if (!SEMVER_REGEX.test(pkg.version)) {
      console.error(
        `❌ Error: Invalid semantic version "${pkg.version}" in package.json`,
      );
      process.exit(1);
    }

    return pkg.version;
  } catch (error) {
    if (error.code === "ENOENT") {
      console.error("❌ Error: package.json not found at", packageJsonPath);
    } else if (error instanceof SyntaxError) {
      console.error("❌ Error: Invalid JSON in package.json");
    } else {
      console.error("❌ Error reading package.json:", error.message);
    }
    process.exit(1);
  }
}

function generateVersionFile(version) {
  // Pure-markdown plugins (e.g. @ogham/prawf) have no `src/`. Skip
  // version.ts generation entirely and sync plugin.json only.
  if (!existsSync(join(ROOT, "src"))) {
    console.log(
      "  ✓ src/ absent — skipping version.ts (markdown-only package)",
    );
    return false;
  }

  const versionFilePath = join(ROOT, "src", "version.ts");

  try {
    let currentVersion = null;
    try {
      const existingContent = readFileSync(versionFilePath, "utf-8");
      const match = existingContent.match(/VERSION = ['"]([^'"]+)['"]/);
      if (match) {
        currentVersion = match[1];
      }
    } catch {
      // File doesn't exist yet
    }

    if (currentVersion === version) {
      console.log(`  ✓ src/version.ts already up to date: ${version}`);
      return false;
    }

    const content = `// Auto-generated by scripts/injectVersion.mjs
// DO NOT EDIT MANUALLY - This file is generated during build

/**
 * Current package version from package.json
 * Automatically synchronized during build process
 */
export const VERSION = '${version}';
`;

    writeFileSync(versionFilePath, content, "utf-8");

    if (currentVersion) {
      console.log(`  ✓ src/version.ts updated: ${currentVersion} → ${version}`);
    } else {
      console.log(`  ✓ src/version.ts created: ${version}`);
    }
    return true;
  } catch (error) {
    console.error("❌ Error generating version file:", error.message);
    process.exit(1);
  }
}

function syncPluginJson(version) {
  const pluginJsonPath = join(ROOT, ".claude-plugin", "plugin.json");

  try {
    const content = readFileSync(pluginJsonPath, "utf-8");
    const plugin = JSON.parse(content);

    if (plugin.version === version) {
      console.log(
        `  ✓ .claude-plugin/plugin.json already up to date: ${version}`,
      );
      return false;
    }

    const prevVersion = plugin.version;
    plugin.version = version;

    writeFileSync(
      pluginJsonPath,
      JSON.stringify(plugin, null, 2) + "\n",
      "utf-8",
    );
    console.log(
      `  ✓ .claude-plugin/plugin.json updated: ${prevVersion} → ${version}`,
    );
    return true;
  } catch (error) {
    if (error.code === "ENOENT") {
      console.error(
        "❌ Error: .claude-plugin/plugin.json not found at",
        pluginJsonPath,
      );
    } else if (error instanceof SyntaxError) {
      console.error("❌ Error: Invalid JSON in plugin.json");
    } else {
      console.error("❌ Error syncing plugin.json:", error.message);
    }
    process.exit(1);
  }
}

/**
 * The generated manifest lives at two paths with identical content — the plugin
 * root copy is agy's marker and is also the one Codex reads (it shadows
 * .codex-plugin). Both must carry the same version or the hosts disagree.
 */
const ADAPTER_MANIFEST_PATHS = ["plugin.json", ".codex-plugin/plugin.json"];

function syncAdapterManifest(relativePath, version) {
  const manifestPath = join(ROOT, relativePath);

  // Adapter manifests are generated per plugin by tools/plugin-compiler;
  // plugins without one (or not yet synced) are skipped silently.
  if (!existsSync(manifestPath)) return false;

  try {
    const content = readFileSync(manifestPath, "utf-8");
    const plugin = JSON.parse(content);

    if (plugin.version === version) {
      console.log(`  ✓ ${relativePath} already up to date: ${version}`);
      return false;
    }

    const prevVersion = plugin.version;
    plugin.version = version;

    writeFileSync(
      manifestPath,
      JSON.stringify(plugin, null, 2) + "\n",
      "utf-8",
    );
    console.log(`  ✓ ${relativePath} updated: ${prevVersion} → ${version}`);
    return true;
  } catch (error) {
    if (error instanceof SyntaxError) {
      console.error(`❌ Error: Invalid JSON in ${relativePath}`);
    } else {
      console.error(`❌ Error syncing ${relativePath}:`, error.message);
    }
    process.exit(1);
  }
}

try {
  const version = readPackageVersion();
  console.log(`\n🔄 Syncing version: ${version}\n`);

  const versionUpdated = generateVersionFile(version);
  const pluginUpdated = syncPluginJson(version);
  const adapterUpdated = ADAPTER_MANIFEST_PATHS.map((path) =>
    syncAdapterManifest(path, version),
  ).some(Boolean);

  if (!versionUpdated && !pluginUpdated && !adapterUpdated) {
    console.log(`\n✅ All versions already synchronized: ${version}`);
  } else {
    console.log(`\n✅ Version synchronization complete: ${version}`);
  }
} catch (error) {
  console.error("❌ Unexpected error:", error.message);
  process.exit(1);
}
