export const ALLOWED_FRACTAL_ROOT_FILES = new Set([
  'index.ts',
  'index.js',
  'index.tsx',
  'index.mjs',
  'index.cjs',
  'main.ts',
  'main.js',
  'INTENT.md',
  'DETAIL.md',
]);

export const FRAMEWORK_RESERVED_FILES: Record<string, string[]> = {
  next: [
    'layout.tsx',
    'layout.ts',
    'layout.js',
    'page.tsx',
    'page.ts',
    'page.js',
    'loading.tsx',
    'loading.ts',
    'error.tsx',
    'error.ts',
    'not-found.tsx',
    'not-found.ts',
    'template.tsx',
    'template.ts',
    'default.tsx',
    'default.ts',
    'route.ts',
    'route.js',
    'middleware.ts',
    'middleware.js',
    'opengraph-image.tsx',
    'opengraph-image.ts',
  ],
  remix: ['root.tsx', 'root.ts', 'entry.client.tsx', 'entry.server.tsx'],
  nuxt: ['app.vue', 'error.vue', 'app.config.ts'],
  sveltekit: [
    '+page.svelte',
    '+page.ts',
    '+page.js',
    '+page.server.ts',
    '+page.server.js',
    '+layout.svelte',
    '+layout.ts',
    '+layout.js',
    '+layout.server.ts',
    '+layout.server.js',
    '+error.svelte',
    '+server.ts',
    '+server.js',
  ],
};

export const FRAMEWORK_PACKAGES: Record<string, string> = {
  next: 'next',
  remix: 'remix',
  '@remix-run/react': 'remix',
  '@remix-run/node': 'remix',
  nuxt: 'nuxt',
  '@sveltejs/kit': 'sveltekit',
};
